name: 'Docs Build & Publish'
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build & Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      # Build
      - name: Install Dependencies
        run: |
          pnpm install 
          pnpm docs:build

      # Upload
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          container_name: $web
          extra_args: '--destination-path fortress-guide.nwest.wiki/ --overwrite'
          connection_string: '${{ secrets.AZURE_CONNECTION_STRING }}'
          source_dir: /dist
          sync: true
